'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { usePortalAuth } from '@/context/PortalAuthContext';
import { listMyBookings, listMyPayments, listPaymentAccounts, submitPaymentConfirmation, uploadPortalMedia } from '@/lib/portalApi';

const rupiah = (value) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0);
const today = new Date().toISOString().slice(0, 10);
const emptyForm = { booking_id: '', bank_account_id: '', jumlah: '', sender_name: '', sender_bank: '', tanggal: today, notes: '', bukti_file: null };

const StepTitle = ({ number, title, description }) => <div className="flex gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-neutral-900 text-xs font-bold text-white">{number}</span><div><h3 className="text-sm font-bold text-neutral-900">{title}</h3><p className="mt-0.5 text-xs leading-5 text-neutral-500">{description}</p></div></div>;

export default function PembayaranPage() {
  const router = useRouter(); const formRef = useRef(null);
  const { jamaah, isLoading: authLoading } = usePortalAuth();
  const [rows, setRows] = useState([]); const [accounts, setAccounts] = useState([]); const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState(null); const [copied, setCopied] = useState('');
  const [form, setForm] = useState(emptyForm);

  useEffect(() => { if (!authLoading && !jamaah) router.replace('/portal/login'); }, [authLoading, jamaah, router]);
  const load = async () => { const [bookings, bankAccounts] = await Promise.all([listMyBookings(), listPaymentAccounts()]); const enriched = await Promise.all((bookings || []).map(async (booking) => { const payments = await listMyPayments(booking.id).catch(() => []); const paid = payments.filter((p) => p.status === 'confirmed').reduce((sum, p) => sum + Number(p.jumlah || 0), 0); return { booking, payments, paid, remaining: Math.max(0, Number(booking.total_harga || 0) - paid) }; })); setRows(enriched); setAccounts(bankAccounts || []); setLoading(false); };
  useEffect(() => { if (jamaah) load().catch(() => setLoading(false)); }, [jamaah]);

  const selectedRow = rows.find((row) => String(row.booking.id) === String(form.booking_id));
  const selectedAccount = accounts.find((account) => String(account.id) === String(form.bank_account_id));
  const totals = useMemo(() => rows.reduce((value, row) => ({ paid: value.paid + row.paid, remaining: value.remaining + row.remaining }), { paid: 0, remaining: 0 }), [rows]);
  const openForm = (bookingId = '') => { setForm({ ...emptyForm, booking_id: bookingId ? String(bookingId) : '' }); setMessage(null); setShowForm(true); setTimeout(() => formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); };

  const submit = async (event) => { event.preventDefault(); setMessage(null); const amount = Number(String(form.jumlah).replace(/\D/g, '')); if (!selectedRow || !selectedAccount || amount <= 0 || amount > selectedRow.remaining || !form.sender_name.trim() || !form.bukti_file) { setMessage({ type: 'error', text: 'Periksa kembali tagihan, rekening tujuan, nominal, nama pengirim, dan bukti transfer.' }); return; } setSubmitting(true); try { const proof = await uploadPortalMedia(form.bukti_file); await submitPaymentConfirmation(form.booking_id, { bank_account_id: Number(form.bank_account_id), jumlah: amount, metode: 'transfer_bank', sender_name: form.sender_name.trim(), sender_bank: form.sender_bank.trim() || null, tanggal: form.tanggal, bukti_url: proof, notes: form.notes.trim() || null, source: 'portal' }); setMessage({ type: 'success', text: 'Bukti pembayaran berhasil dikirim. Admin akan memeriksanya terlebih dahulu.' }); setShowForm(false); setForm(emptyForm); await load(); window.scrollTo({ top: 0, behavior: 'smooth' }); } catch (error) { setMessage({ type: 'error', text: error.message }); } finally { setSubmitting(false); } };
  const copyAccount = async (account) => { await navigator.clipboard.writeText(account.account_number); setCopied(String(account.id)); setTimeout(() => setCopied(''), 1600); };

  if (authLoading || !jamaah) return <div className="flex min-h-[70vh] items-center justify-center text-sm text-neutral-500">Memuat pembayaran...</div>;
  return <main className="space-y-5 px-4 py-5">
    <section className="overflow-hidden rounded-2xl bg-neutral-900 p-5 text-white"><p className="text-xs font-medium text-neutral-300">Ringkasan semua booking</p><div className="mt-4 grid grid-cols-2 gap-4"><div><p className="text-[11px] text-neutral-400">Sudah dibayar</p><p className="mt-1 text-lg font-bold">{rupiah(totals.paid)}</p></div><div className="border-l border-white/15 pl-4"><p className="text-[11px] text-neutral-400">Sisa tagihan</p><p className="mt-1 text-lg font-bold">{rupiah(totals.remaining)}</p></div></div></section>
    {message && <div role="status" className={`rounded-xl border p-4 text-sm leading-6 ${message.type === 'success' ? 'border-success-200 bg-success-50 text-success-700' : 'border-danger-200 bg-danger-50 text-danger-700'}`}>{message.text}</div>}
    {!showForm && totals.remaining > 0 && <section className="rounded-2xl border border-neutral-200 bg-white p-4"><h2 className="font-bold text-neutral-900">Sudah melakukan transfer?</h2><p className="mt-1 text-xs leading-5 text-neutral-500">Kirim bukti agar pembayaran dapat diverifikasi oleh admin.</p><button type="button" onClick={() => openForm()} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3.5 text-sm font-bold text-white"><span className="text-lg leading-none">+</span> Konfirmasi transfer baru</button><div className="mt-4 flex items-center justify-between text-center text-[10px] text-neutral-500"><span>Pilih tagihan</span><span>→</span><span>Pilih rekening</span><span>→</span><span>Upload bukti</span></div></section>}

    {showForm && <form ref={formRef} onSubmit={submit} className="scroll-mt-20 space-y-5 rounded-2xl border border-neutral-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-neutral-900">Konfirmasi Transfer</h2><p className="mt-1 text-xs text-neutral-500">Data akan diperiksa sebelum mengurangi tagihan.</p></div><button type="button" aria-label="Tutup form" onClick={() => setShowForm(false)} className="flex h-9 w-9 items-center justify-center rounded-full bg-neutral-100 text-xl text-neutral-500">×</button></div>
      <div className="space-y-3"><StepTitle number="1" title="Pilih tagihan" description="Pilih paket yang sudah Anda transfer."/><select required value={form.booking_id} onChange={(e) => setForm({ ...form, booking_id: e.target.value, jumlah: '' })} className="w-full rounded-xl border border-neutral-300 bg-white px-3 py-3 text-sm"><option value="">Pilih booking</option>{rows.filter((row) => row.remaining > 0).map((row) => <option key={row.booking.id} value={row.booking.id}>{row.booking.jadwal_nama} — {rupiah(row.remaining)}</option>)}</select>{selectedRow && <div className="flex justify-between rounded-xl bg-warning-50 p-3 text-xs"><span className="text-warning-700">Sisa tagihan</span><strong className="text-warning-800">{rupiah(selectedRow.remaining)}</strong></div>}</div>
      <div className="space-y-3"><StepTitle number="2" title="Pilih rekening tujuan" description="Pilih rekening yang sama dengan tujuan transfer Anda."/><div className="space-y-2">{accounts.length === 0 ? <div className="rounded-xl border border-dashed border-neutral-300 p-4 text-center text-xs text-neutral-500">Belum ada rekening aktif. Hubungi admin travel.</div> : accounts.map((account) => <label key={account.id} className={`block cursor-pointer rounded-xl border p-4 transition-colors ${String(form.bank_account_id) === String(account.id) ? 'border-brand bg-neutral-50' : 'border-neutral-200'}`}><div className="flex gap-3"><input type="radio" name="bank" value={account.id} checked={String(form.bank_account_id) === String(account.id)} onChange={(e) => setForm({ ...form, bank_account_id: e.target.value })}/><div className="min-w-0 flex-1"><p className="text-sm font-bold text-neutral-900">{account.bank_name}</p><p className="mt-1 font-mono text-base font-bold tracking-wide text-neutral-800">{account.account_number}</p><p className="mt-1 text-xs text-neutral-500">a.n. {account.account_holder}</p></div><button type="button" onClick={(e) => { e.preventDefault(); copyAccount(account); }} className="h-fit rounded-lg border border-neutral-300 bg-white px-2.5 py-2 text-[11px] font-bold text-neutral-700">{copied === String(account.id) ? 'Tersalin' : 'Salin'}</button></div></label>)}</div></div>
      <div className="space-y-3"><StepTitle number="3" title="Isi detail dan bukti" description="Gunakan data yang sama seperti pada struk transfer."/><label className="block text-xs font-semibold text-neutral-700">Nominal transfer<div className="mt-1 flex rounded-xl border border-neutral-300 bg-white"><span className="flex items-center border-r border-neutral-200 px-3 text-sm text-neutral-500">Rp</span><input required inputMode="numeric" value={form.jumlah ? Number(form.jumlah.replace(/\D/g, '')).toLocaleString('id-ID') : ''} onChange={(e) => setForm({ ...form, jumlah: e.target.value.replace(/\D/g, '') })} className="min-w-0 flex-1 rounded-r-xl px-3 py-3 text-sm outline-none" placeholder="0" /></div></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-neutral-700">Nama pengirim<input required value={form.sender_name} onChange={(e) => setForm({ ...form, sender_name: e.target.value })} className="mt-1 w-full rounded-xl border border-neutral-300 px-3 py-3 text-sm" /></label><label className="text-xs font-semibold text-neutral-700">Tanggal<input required type="date" max={today} value={form.tanggal} onChange={(e) => setForm({ ...form, tanggal: e.target.value })} className="mt-1 w-full rounded-xl border border-neutral-300 px-3 py-3 text-sm" /></label></div><label className="block text-xs font-semibold text-neutral-700">Bank pengirim <span className="font-normal text-neutral-400">(opsional)</span><input value={form.sender_bank} onChange={(e) => setForm({ ...form, sender_bank: e.target.value })} className="mt-1 w-full rounded-xl border border-neutral-300 px-3 py-3 text-sm" placeholder="Contoh: BCA" /></label><label className={`block cursor-pointer rounded-xl border-2 border-dashed p-5 text-center ${form.bukti_file ? 'border-success-300 bg-success-50' : 'border-neutral-300 bg-neutral-50'}`}><span className="block text-sm font-bold text-neutral-800">{form.bukti_file ? form.bukti_file.name : 'Pilih bukti transfer'}</span><span className="mt-1 block text-xs text-neutral-500">JPG, PNG, WEBP, atau PDF · maksimal 25 MB</span><input required type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={(e) => setForm({ ...form, bukti_file: e.target.files?.[0] || null })} className="sr-only" /></label></div>
      <button disabled={submitting || accounts.length === 0} className="w-full rounded-xl bg-brand px-4 py-3.5 text-sm font-bold text-white disabled:opacity-60">{submitting ? 'Mengunggah dan mengirim...' : 'Kirim untuk diverifikasi'}</button><p className="text-center text-[11px] leading-5 text-neutral-400">Pembayaran belum mengurangi tagihan sebelum dikonfirmasi admin.</p>
    </form>}

    <section className="space-y-3"><div><h2 className="font-bold text-neutral-900">Tagihan Saya</h2><p className="mt-1 text-xs text-neutral-500">Pilih tagihan untuk melihat riwayat lengkap.</p></div>{loading ? <div className="h-32 animate-pulse rounded-2xl bg-neutral-100" /> : rows.length === 0 ? <div className="rounded-2xl border border-dashed border-neutral-300 p-8 text-center text-sm text-neutral-500">Belum ada booking.</div> : rows.map(({ booking, payments, paid, remaining }) => <article key={booking.id} className="rounded-2xl border border-neutral-200 bg-white p-4"><Link href={`/portal/booking/${booking.id}`} className="block"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-sm font-bold text-neutral-900">{booking.jadwal_nama}</h3><p className="mt-1 text-xs text-neutral-500">Terkonfirmasi {rupiah(paid)}</p></div><span className={`shrink-0 text-sm font-bold ${remaining === 0 ? 'text-success-700' : 'text-warning-700'}`}>{remaining === 0 ? 'Lunas' : rupiah(remaining)}</span></div>{payments.some((payment) => payment.status === 'pending') && <span className="mt-3 inline-flex rounded-full bg-warning-50 px-2 py-1 text-[10px] font-bold text-warning-700">Menunggu verifikasi</span>}{payments.some((payment) => payment.status === 'rejected') && <span className="ml-2 mt-3 inline-flex rounded-full bg-danger-50 px-2 py-1 text-[10px] font-bold text-danger-700">Ada yang ditolak</span>}</Link>{remaining > 0 && <button type="button" onClick={() => openForm(booking.id)} className="mt-4 w-full rounded-xl border border-brand px-3 py-2.5 text-xs font-bold text-brand">Bayar tagihan ini</button>}</article>)}</section>
  </main>;
}
